apiVersion: v1
kind: Pod
metadata:
  name: webpodtest
  labels:
    name: web
spec:
  containers:
    - name: test
      image: gcr.io/my-project-1489935859077/myappsecret:v1
      env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: dbname
      envFrom:
      - configMapRef:
          name: special-config
  restartPolicy: Never
